system/udisks-glue: Removed (build failure)
This one is probably easy-ish to fix, but it would require
some interest on the part of the fixer.  I don't personally
need this, so it won't be me.

main.c:171:5: error: ‘g_type_init’ is deprecated
cc1: all warnings being treated as errors

Signed-off-by: Robby Workman <rworkman@slackbuilds.org>