python/python-mpmath: Add missing setuptools-scm dep.
This is declared upstream here:

https://github.com/fredrik-johansson/mpmath/blob/1.2.1/setup.cfg#L30

If setuptools-scm is not installed, the build will try to downloaad
it as root when it runs. This means you cannot build this package
without internet access.

```
distutils.errors.DistutilsError: Command '['/usr/bin/python2', '-m',
'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w',
'/tmp/SBo/build_python-mpmath/tmpymNMLJ', '--quiet',
'setuptools_scm>=1.7.0']' returned non-zero exit status 1
```

Signed-off-by: Andrew Clemons <andrew.clemons@gmail.com>

Signed-off-by: Willy Sudiarto Raharjo <willysr@slackbuilds.org>